name: news
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  dio: ^5.3.3
  freezed_annotation: ^2.4.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3  
  flutter_localizations:
    sdk: flutter
  geocoding: ^2.1.0  
  geolocator: ^10.1.0
  get_it: ^7.6.4
  go_router: ^11.1.2  
  slang: ^3.24.0
  slang_flutter: ^3.24.0
  news_ui:
    path: packages/news_ui

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  freezed: ^2.4.3
  json_serializable: ^6.7.1
  slang_build_runner: ^3.24.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
