include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    file_names: false
    always_put_required_named_parameters_first: false
    avoid_positional_boolean_parameters: false
    avoid_dynamic_calls: false
    overridden_fields: false
    unawaited_futures: false
    lines_longer_than_80_chars: false
    use_build_context_synchronously: false
    annotate_overrides: false
    prefer_if_elements_to_conditional_expressions: false
    always_use_package_imports: false
    public_member_api_docs: false
    unnecessary_lambdas: false
    use_late_for_private_fields_and_variables: false
    one_member_abstracts: false

analyzer:
  errors:
    unused_import: error
    invalid_annotation_target: ignore
    sort_pub_dependencies: ignore
    avoid_renaming_method_parameters: ignore
    type_annotate_public_apis: ignore
