name: news_ui
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  cached_network_image: ^3.3.0
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  intl: ^0.18.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter_gen:
  output: lib/src/gen/

  integrations:
    flutter_svg: true

  assets:
    outputs:
      package_parameter_enabled: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/svgs/

  fonts:
    - family: NewYork
      fonts:
        - asset: lib/src/typography/fonts/new_york/NewYork-Bold.ttf
        - asset: lib/src/typography/fonts/new_york/NewYork-SemiBold.ttf

    - family: Nunito
      fonts:
        - asset: lib/src/typography/fonts/nunito/Nunito-Black.ttf
        - asset: lib/src/typography/fonts/nunito/Nunito-Bold.ttf
        - asset: lib/src/typography/fonts/nunito/Nunito-ExtraBold.ttf
        - asset: lib/src/typography/fonts/nunito/Nunito-Light.ttf
        - asset: lib/src/typography/fonts/nunito/Nunito-Regular.ttf
        - asset: lib/src/typography/fonts/nunito/Nunito-SemiBold.ttf      

    - family: NewsIcons
      fonts:
        - asset: assets/icons/NewsIcons.ttf  
